version: '3'

services:
  scientist:
    image: scientist:latest
    build:
      context: ./
    volumes:
      - ./:/app
    depends_on:
      - database
    networks:
      - frontend
      - backend
    restart: always
    ports:
      - "80:8000"

  database:
    image: mysql:5.6
    volumes:
      - ./storage/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    env_file:
      - .env

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
